version: '3'
services:
  bd1_python:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/app/
    ports:
      - 5000:5000
    network_mode: "host"
    working_dir: /var/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run
